export const PROFILE_ACTIONS = {
  USER_INFO_RETRIEVED: 'user.info.retrieved',
  USER_INFO_FAILED: 'user.info.failed',
  OUTBOUND_CALL_OPTIONS_RETRIEVED: 'outboundcalloptions.retrieved',
  OUTBOUND_CALL_OPTIONS_FAILED: 'outboundcalloptions.failed',
  SELECTED_OUTBOUND_CALL_OPTION_RETRIEVED: 'selectedoutboundcalloption.retrieved',
  SELECTED_OUTBOUND_CALL_OPTION_FAILED: 'selectedoutboundcalloption.failed',
  OUTBOUND_PRIVATE_CALL_OPTION_SELECTED: 'outboundprivatecalloption.selected',
  OUTBOUND_CALL_OPTION_SELECTED: 'outboundcalloption.selected',
  CHANGE_EDIT_STATE_SELECTED: 'edit.state.selected',
  CHANGE_PASSWORD_SUCCESSFUL: 'change.password.successful',
  CHANGE_PASSWORD_FAILED: 'change.password.failed',
  CHANGE_EMAIL_SUCCESSFUL: 'change.email.successful',
  CHANGE_EMAIL_FAILED: 'change.email.failed',
  CHANGE_USERNAME_SUCCESSFUL: 'change.username.successful',
  CHANGE_USERNAME_FAILED: 'change.username.failed',
  CHANGE_USER_INFO_SUCCESSFUL: 'change.user.info.successful',
  CHANGE_USER_INFO_FAILED: 'change.user.info.failed',
  SET_ERROR: 'error.set',
  CLEAR_PASSWORD: 'clear.password',
  PASSWORD_CHECK: 'check.password',
  CHANGING_PROFILE_PICTURE: 'changing.profile.picture',
  CHANGE_PROFILE_PICTURE_SUCCESSFUL: 'change.profile.picture.successful',
	RETRIEVE_ORGANISATION_PROFILE_PICTURE_SUCCESSFUL: 'retrieve.organisation.profile.picture.successful',
	RETRIEVE_ORGANISATION_PROFILE_PICTURE_FAIL: 'retrieve.organisation.profile.picture.fail',
	RETRIEVE_PERSONAL_INFO: 'retrieve.profile.personal.info',
  
  RETRIEVE_MEMBER_COMMS: 'member.comms.retrieve'
};
